site_name: DEFCON-0 Build
repo_name: neumj/defcon-build
repo_url: https://github.com/neumj/cortez
copyright: Copyright &copy; 2023 - Neumann/Popov
    
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/pirate-50.png
  favicon: assets/pirate-50.png
  features:
    - content.tabs.link
    - navigation.footer
    - search.highlight

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: datetime
      timezone: America/New_York
  - with-pdf:
      author: Neumann, Popov
      cover: true
      back_cover: false
      cover_title: Our Log of The Sea of Cortez
      cover_subtitle: June 2023

extra:
  generator: false

nav:
    - Home: index.md
    - La Paz: La_Paz_20230616.md
    - La Paz: La_Paz_20230617.md
    - Ensenada Grande: Ensenada_Grande_20230618.md
    - Isla San Francisco: Isla_San_Francisco_20230619.md
    - San Evaristo: San_Evaristo_20230620.md
    - Caleta Partida: Caleta_Partida_20230621.md
    - Ensenada Candelero: Ensenada_Candelero_20230622.md
    - Caleta Lobos: Caleta_Lobos_20230623.md
    - La Paz: La_Paz_20230624.md
    - Photo Gallery: Photo_Gallery.md
    - Entries by Tags: tags.md